version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql8
    volumes:
      - ./data/mysql/data/mysql:/var/lib/mysql
      - ./data/mysql/data/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      POSTGRES_PASSWORD: Q2eywi5dpX1nciNj906faYHGXoWUhR1R
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:6-alpine
    container_name: redis
    volumes:
      - ./data/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
